/* ================================================================
   TentacleWars World 1 levels

   Owns the authored World 1 reconstruction slice used by the
   separate TentacleWars campaign track.
   ================================================================ */

export const TW_WORLD_1_LEVELS = Object.freeze([
  Object.freeze({
    id: 'W1-01',
    world: 1,
    phase: 1,
    energyCap: 30,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 30, x: 0.60, y: 0.42 },
      { id: 'r1', owner: 'red', initialEnergy: 5, x: 0.39, y: 0.50 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 18,
    introMechanicTags: ['connect'],
  }),
  Object.freeze({
    id: 'W1-02',
    world: 1,
    phase: 2,
    energyCap: 50,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 20, x: 0.57, y: 0.59 },
      { id: 'r1', owner: 'red', initialEnergy: 5, x: 0.50, y: 0.39 },
      { id: 'r2', owner: 'red', initialEnergy: 10, x: 0.38, y: 0.58 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 40,
    introMechanicTags: ['priority-target'],
  }),
  Object.freeze({
    id: 'W1-03',
    world: 1,
    phase: 3,
    energyCap: 70,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 30, x: 0.72, y: 0.64 },
      { id: 'n1', owner: 'neutral', initialEnergy: 5, x: 0.52, y: 0.22 },
      { id: 'n2', owner: 'neutral', initialEnergy: 5, x: 0.38, y: 0.60 },
      { id: 'r1', owner: 'red', initialEnergy: 30, x: 0.21, y: 0.22 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 70,
    introMechanicTags: ['slice', 'pulsar-class'],
  }),
  Object.freeze({
    id: 'W1-04',
    world: 1,
    phase: 4,
    energyCap: 50,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 18, x: 0.50, y: 0.52 },
      { id: 'n1', owner: 'neutral', initialEnergy: 5, x: 0.27, y: 0.29 },
      { id: 'n2', owner: 'neutral', initialEnergy: 5, x: 0.59, y: 0.19 },
      { id: 'r1', owner: 'red', initialEnergy: 30, x: 0.54, y: 0.86 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 75,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-05',
    world: 1,
    phase: 5,
    energyCap: 60,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 15, x: 0.27, y: 0.55 },
      { id: 'n1', owner: 'neutral', initialEnergy: 5, x: 0.31, y: 0.35 },
      { id: 'n2', owner: 'neutral', initialEnergy: 5, x: 0.50, y: 0.80 },
      { id: 'r1', owner: 'red', initialEnergy: 60, x: 0.74, y: 0.59 },
    ],
    obstacles: [
      {
        id: 'o1',
        shape: {
          kind: 'capsule',
          ax: 0.58,
          ay: 0.16,
          bx: 0.60,
          by: 0.30,
          radius: 0.020,
        },
      },
      {
        id: 'o2',
        shape: {
          kind: 'capsule',
          ax: 0.52,
          ay: 0.69,
          bx: 0.63,
          by: 0.77,
          radius: 0.020,
        },
      },
    ],
    winCondition: 'all_hostiles_converted',
    par: 100,
    introMechanicTags: ['obstacle-routing'],
  }),
  Object.freeze({
    id: 'W1-06',
    world: 1,
    phase: 6,
    energyCap: 100,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 80, x: 0.14, y: 0.28 },
      { id: 'p2', owner: 'player', initialEnergy: 80, x: 0.14, y: 0.72 },
      { id: 'n1', owner: 'neutral', initialEnergy: 40, x: 0.42, y: 0.18 },
      { id: 'n2', owner: 'neutral', initialEnergy: 40, x: 0.42, y: 0.82 },
      { id: 'r1', owner: 'red', initialEnergy: 36, x: 0.82, y: 0.50 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 127,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-07',
    world: 1,
    phase: 7,
    energyCap: 100,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 80, x: 0.14, y: 0.50 },
      { id: 'n1', owner: 'neutral', initialEnergy: 40, x: 0.42, y: 0.24 },
      { id: 'n2', owner: 'neutral', initialEnergy: 40, x: 0.42, y: 0.76 },
      { id: 'r1', owner: 'red', initialEnergy: 40, x: 0.72, y: 0.26 },
      { id: 'r2', owner: 'red', initialEnergy: 40, x: 0.72, y: 0.74 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 117,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-08',
    world: 1,
    phase: 8,
    energyCap: 60,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 50, x: 0.14, y: 0.50 },
      { id: 'p2', owner: 'player', initialEnergy: 48, x: 0.28, y: 0.18 },
      { id: 'n1', owner: 'neutral', initialEnergy: 48, x: 0.50, y: 0.18 },
      { id: 'n2', owner: 'neutral', initialEnergy: 48, x: 0.50, y: 0.82 },
      { id: 'r1', owner: 'red', initialEnergy: 24, x: 0.80, y: 0.30 },
      { id: 'r2', owner: 'red', initialEnergy: 30, x: 0.80, y: 0.70 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 66,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-09',
    world: 1,
    phase: 9,
    energyCap: 150,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 120, x: 0.14, y: 0.50 },
      { id: 'n1', owner: 'neutral', initialEnergy: 80, x: 0.36, y: 0.22 },
      { id: 'n2', owner: 'neutral', initialEnergy: 80, x: 0.36, y: 0.78 },
      { id: 'r1', owner: 'red', initialEnergy: 60, x: 0.58, y: 0.50 },
      { id: 'r2', owner: 'red', initialEnergy: 30, x: 0.84, y: 0.26 },
      { id: 'r3', owner: 'red', initialEnergy: 30, x: 0.84, y: 0.74 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 157,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-10',
    world: 1,
    phase: 10,
    energyCap: 80,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 64, x: 0.12, y: 0.28 },
      { id: 'p2', owner: 'player', initialEnergy: 64, x: 0.12, y: 0.72 },
      { id: 'n1', owner: 'neutral', initialEnergy: 48, x: 0.38, y: 0.50 },
      { id: 'r1', owner: 'red', initialEnergy: 32, x: 0.60, y: 0.18 },
      { id: 'r2', owner: 'red', initialEnergy: 32, x: 0.60, y: 0.82 },
      { id: 'r3', owner: 'red', initialEnergy: 40, x: 0.84, y: 0.50 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 80,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-11',
    world: 1,
    phase: 11,
    energyCap: 60,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 36, x: 0.12, y: 0.20 },
      { id: 'p2', owner: 'player', initialEnergy: 36, x: 0.12, y: 0.80 },
      { id: 'n1', owner: 'neutral', initialEnergy: 28, x: 0.34, y: 0.50 },
      { id: 'n2', owner: 'neutral', initialEnergy: 28, x: 0.52, y: 0.20 },
      { id: 'n3', owner: 'neutral', initialEnergy: 28, x: 0.52, y: 0.80 },
      { id: 'r1', owner: 'red', initialEnergy: 18, x: 0.82, y: 0.20 },
      { id: 'r2', owner: 'red', initialEnergy: 18, x: 0.82, y: 0.80 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 61,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-12',
    world: 1,
    phase: 12,
    energyCap: 100,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 60, x: 0.12, y: 0.50 },
      { id: 'n1', owner: 'neutral', initialEnergy: 36, x: 0.34, y: 0.20 },
      { id: 'n2', owner: 'neutral', initialEnergy: 36, x: 0.34, y: 0.80 },
      { id: 'r1', owner: 'red', initialEnergy: 24, x: 0.56, y: 0.22 },
      { id: 'r2', owner: 'red', initialEnergy: 24, x: 0.56, y: 0.78 },
      { id: 'r3', owner: 'red', initialEnergy: 50, x: 0.82, y: 0.50 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 102,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-13',
    world: 1,
    phase: 13,
    energyCap: 150,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 90, x: 0.12, y: 0.24 },
      { id: 'p2', owner: 'player', initialEnergy: 90, x: 0.12, y: 0.76 },
      { id: 'n1', owner: 'neutral', initialEnergy: 60, x: 0.34, y: 0.50 },
      { id: 'r1', owner: 'red', initialEnergy: 40, x: 0.62, y: 0.20 },
      { id: 'r2', owner: 'red', initialEnergy: 40, x: 0.62, y: 0.80 },
      { id: 'r3', owner: 'red', initialEnergy: 45, x: 0.84, y: 0.50 },
    ],
    obstacles: [
      {
        id: 'o1',
        shape: { kind: 'capsule', ax: 0.46, ay: 0.25, bx: 0.46, by: 0.39, radius: 0.020 },
      },
      {
        id: 'o2',
        shape: { kind: 'capsule', ax: 0.46, ay: 0.61, bx: 0.46, by: 0.75, radius: 0.020 },
      },
    ],
    winCondition: 'all_hostiles_converted',
    par: 154,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-14',
    world: 1,
    phase: 14,
    energyCap: 150,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 90, x: 0.12, y: 0.50 },
      { id: 'n1', owner: 'neutral', initialEnergy: 60, x: 0.30, y: 0.18 },
      { id: 'n2', owner: 'neutral', initialEnergy: 60, x: 0.30, y: 0.82 },
      { id: 'n3', owner: 'neutral', initialEnergy: 75, x: 0.54, y: 0.50 },
      { id: 'r1', owner: 'red', initialEnergy: 45, x: 0.78, y: 0.24 },
      { id: 'r2', owner: 'red', initialEnergy: 45, x: 0.78, y: 0.76 },
    ],
    obstacles: [
      {
        id: 'o1',
        shape: { kind: 'capsule', ax: 0.42, ay: 0.27, bx: 0.42, by: 0.41, radius: 0.020 },
      },
      {
        id: 'o2',
        shape: { kind: 'capsule', ax: 0.42, ay: 0.59, bx: 0.42, by: 0.73, radius: 0.020 },
      },
    ],
    winCondition: 'all_hostiles_converted',
    par: 155,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-15',
    world: 1,
    phase: 15,
    energyCap: 100,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 60, x: 0.12, y: 0.22 },
      { id: 'p2', owner: 'player', initialEnergy: 60, x: 0.12, y: 0.78 },
      { id: 'n1', owner: 'neutral', initialEnergy: 48, x: 0.34, y: 0.50 },
      { id: 'n2', owner: 'neutral', initialEnergy: 40, x: 0.54, y: 0.18 },
      { id: 'n3', owner: 'neutral', initialEnergy: 40, x: 0.54, y: 0.82 },
      { id: 'r1', owner: 'red', initialEnergy: 30, x: 0.84, y: 0.20 },
      { id: 'r2', owner: 'red', initialEnergy: 30, x: 0.84, y: 0.80 },
    ],
    obstacles: [
      {
        id: 'o1',
        shape: { kind: 'capsule', ax: 0.44, ay: 0.28, bx: 0.46, by: 0.42, radius: 0.020 },
      },
      {
        id: 'o2',
        shape: { kind: 'capsule', ax: 0.46, ay: 0.58, bx: 0.44, by: 0.72, radius: 0.020 },
      },
      {
        id: 'o3',
        shape: { kind: 'capsule', ax: 0.59, ay: 0.50, bx: 0.73, by: 0.50, radius: 0.020 },
      },
    ],
    winCondition: 'all_hostiles_converted',
    par: 104,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-16',
    world: 1,
    phase: 16,
    energyCap: 30,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 25, x: 0.12, y: 0.50 },
      { id: 'n1', owner: 'neutral', initialEnergy: 10, x: 0.30, y: 0.20 },
      { id: 'n2', owner: 'neutral', initialEnergy: 10, x: 0.30, y: 0.80 },
      { id: 'r1', owner: 'red', initialEnergy: 12, x: 0.56, y: 0.20 },
      { id: 'r2', owner: 'red', initialEnergy: 12, x: 0.56, y: 0.80 },
      { id: 'r3', owner: 'red', initialEnergy: 15, x: 0.84, y: 0.50 },
    ],
    obstacles: [
      {
        id: 'o1',
        shape: { kind: 'capsule', ax: 0.42, ay: 0.17, bx: 0.46, by: 0.31, radius: 0.020 },
      },
      {
        id: 'o2',
        shape: { kind: 'capsule', ax: 0.46, ay: 0.69, bx: 0.42, by: 0.83, radius: 0.020 },
      },
      {
        id: 'o3',
        shape: { kind: 'capsule', ax: 0.64, ay: 0.29, bx: 0.68, by: 0.43, radius: 0.020 },
      },
      {
        id: 'o4',
        shape: { kind: 'capsule', ax: 0.68, ay: 0.57, bx: 0.64, by: 0.71, radius: 0.020 },
      },
    ],
    winCondition: 'all_hostiles_converted',
    par: 31,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-17',
    world: 1,
    phase: 17,
    energyCap: 70,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 30, x: 0.12, y: 0.20 },
      { id: 'p2', owner: 'player', initialEnergy: 30, x: 0.12, y: 0.80 },
      { id: 'n1', owner: 'neutral', initialEnergy: 24, x: 0.32, y: 0.50 },
      { id: 'r1', owner: 'red', initialEnergy: 14, x: 0.54, y: 0.18 },
      { id: 'r2', owner: 'red', initialEnergy: 14, x: 0.54, y: 0.82 },
      { id: 'r3', owner: 'red', initialEnergy: 14, x: 0.76, y: 0.18 },
      { id: 'r4', owner: 'red', initialEnergy: 14, x: 0.76, y: 0.82 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 74,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-18',
    world: 1,
    phase: 18,
    energyCap: 200,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 80, x: 0.12, y: 0.50 },
      { id: 'p2', owner: 'player', initialEnergy: 80, x: 0.22, y: 0.18 },
      { id: 'p3', owner: 'player', initialEnergy: 80, x: 0.22, y: 0.82 },
      { id: 'n1', owner: 'neutral', initialEnergy: 70, x: 0.42, y: 0.50 },
      { id: 'r1', owner: 'red', initialEnergy: 40, x: 0.62, y: 0.22 },
      { id: 'r2', owner: 'red', initialEnergy: 40, x: 0.62, y: 0.78 },
      { id: 'r3', owner: 'red', initialEnergy: 56, x: 0.84, y: 0.50 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 211,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-19',
    world: 1,
    phase: 19,
    energyCap: 100,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 45, x: 0.12, y: 0.20 },
      { id: 'p2', owner: 'player', initialEnergy: 45, x: 0.12, y: 0.80 },
      { id: 'p3', owner: 'player', initialEnergy: 40, x: 0.28, y: 0.50 },
      { id: 'n1', owner: 'neutral', initialEnergy: 35, x: 0.46, y: 0.20 },
      { id: 'n2', owner: 'neutral', initialEnergy: 35, x: 0.46, y: 0.80 },
      { id: 'r1', owner: 'red', initialEnergy: 22, x: 0.68, y: 0.22 },
      { id: 'r2', owner: 'red', initialEnergy: 22, x: 0.68, y: 0.78 },
      { id: 'r3', owner: 'red', initialEnergy: 30, x: 0.86, y: 0.50 },
    ],
    obstacles: [],
    winCondition: 'all_hostiles_converted',
    par: 106,
    introMechanicTags: [],
  }),
  Object.freeze({
    id: 'W1-20',
    world: 1,
    phase: 20,
    energyCap: 200,
    cells: [
      { id: 'p1', owner: 'player', initialEnergy: 80, x: 0.10, y: 0.18 },
      { id: 'p2', owner: 'player', initialEnergy: 80, x: 0.10, y: 0.82 },
      { id: 'p3', owner: 'player', initialEnergy: 70, x: 0.24, y: 0.50 },
      { id: 'n1', owner: 'neutral', initialEnergy: 60, x: 0.38, y: 0.22 },
      { id: 'n2', owner: 'neutral', initialEnergy: 60, x: 0.38, y: 0.78 },
      { id: 'r1', owner: 'red', initialEnergy: 35, x: 0.60, y: 0.18 },
      { id: 'r2', owner: 'red', initialEnergy: 35, x: 0.60, y: 0.82 },
      { id: 'r3', owner: 'red', initialEnergy: 50, x: 0.76, y: 0.50 },
      { id: 'r4', owner: 'red', initialEnergy: 64, x: 0.90, y: 0.50 },
    ],
    obstacles: [
      {
        id: 'o1',
        shape: { kind: 'capsule', ax: 0.49, ay: 0.25, bx: 0.51, by: 0.39, radius: 0.020 },
      },
      {
        id: 'o2',
        shape: { kind: 'capsule', ax: 0.51, ay: 0.61, bx: 0.49, by: 0.75, radius: 0.020 },
      },
      {
        id: 'o3',
        shape: { kind: 'capsule', ax: 0.63, ay: 0.50, bx: 0.77, by: 0.50, radius: 0.020 },
      },
    ],
    winCondition: 'all_hostiles_converted',
    par: 219,
    introMechanicTags: [],
  }),
]);

export const TW_WORLD_1_PROTOTYPE_LEVELS = Object.freeze(
  TW_WORLD_1_LEVELS.slice(0, 5),
);
